/**:
    ros__parameters:
        use_sim_time: true                # 使用仿真时间

        # use_imu_as_input: true            # 使用IMU作为输入
        runtime_pos_log_enable: false      # 运行时位置日志启用

        filter_size_surf_min: 0.2         # 表面最小滤波尺寸
        filter_size_map_min: 0.2          # 地图最小滤波尺寸

        common:
            lid_topic: "/hesai_go2/transformed_cloud"  # 激光雷达话题                     （要调整）
            imu_topic: "/hesai_go2/transformed_imu"    # IMU话题                         （要调整）
            con_frame: false               # 是否需要将多个激光雷达帧合并为一个
            con_frame_num: 1               # 合并的帧数
            cut_frame: false               # 是否需要将一个激光雷达帧切分为多个子帧
            cut_frame_time_interval: 0.1   # 应该是激光雷达频率的整数分之一
            time_lag_imu_to_lidar: 0.0    # 由其他算法(如LI-Init)校准的激光雷达和IMU之间的时间偏移
                                          # 通过减去此值将IMU的时间样本从当前时间线转换到激光雷达的时间线

        preprocess:
            lidar_type: 4                  # 激光雷达类型           （未知，需确认）
            scan_line: 16                  # 扫描线数              （未知，需确认）
            timestamp_unit: 0              # PointCloud2话题中time/t字段的单位：0-秒，1-毫秒，2-微秒，3-纳秒 （可能要调整）
            blind: 0.5                     # 盲区距离               （可能要调整）

        mapping:
            imu_en: true                   # 启用IMU
            start_in_aggressive_motion: false  # 如果为true，需要在下面提供预知的重力值
            extrinsic_est_en: false        # 对于剧烈运动，设置为false
            imu_time_inte: 0.002            # IMU频率的倒数                 
            satu_acc: 30.0                 # IMU加速度的饱和值，与单位无关   
            satu_gyro: 35.0                # IMU角速度的饱和值，与单位无关   
            acc_norm: 9.81                 # IMU加速度单位：1.0表示以g为单位，9.81表示以m/s^2为单位   
            lidar_meas_cov: 0.01           # 激光雷达测量协方差
            acc_cov_output: 500.0          # 加速度输出协方差
            gyr_cov_output: 1000.0         # 陀螺仪输出协方差
            b_acc_cov: 0.0001              # 加速度偏置协方差
            b_gyr_cov: 0.0001              # 陀螺仪偏置协方差
            imu_meas_acc_cov: 0.1          # IMU加速度测量协方差
            imu_meas_omg_cov: 0.1          # IMU角速度测量协方差
            gyr_cov_input: 0.01            # IMU作为输入模型时的陀螺仪协方差
            acc_cov_input: 0.1             # IMU作为输入模型时的加速度协方差
            plane_thr: 0.1                 # 平面判定阈值，越小表示平面越平
            match_s: 81.0                  # 匹配分数
            fov_degree: 180.0              # 视场角度
            det_range: 100.0               # 检测范围
            gravity_align: false           # 世界坐标系的z轴是否与重力方向对齐
            gravity: [0.0, 0.0, 0.0]       # 需要对齐的重力方向
            gravity_init: [0.0, 0.0, 0.0]  # 第一个IMU体坐标系中的预知重力值
            
            # IMU到激光雷达的转换
            extrinsic_T: [ 0.1710, 0.0, 0.0908]  # 平移向量                   
            extrinsic_R: [  1.0, 0.0, 0.0,                # 旋转矩阵
                            0.0, 1.0, 0.0,
                            0.0, 0.0, 1.0 ]

        odometry: 
            publish_odometry_without_downsample: true   # 发布未降采样的里程计数据

        publish:
            path_en: true                # 是否发布路径输出
            scan_publish_en: true          # 是否发布点云输出
            scan_bodyframe_pub_en: false   # 是否在IMU体坐标系中输出点云扫描

        pcd_save:
            pcd_save_en: true              # 保存地图到pcd文件
            interval: -1                   # 每个pcd文件保存的激光雷达帧数
                                          # -1：所有帧都保存在一个pcd文件中，帧数过多可能导致内存崩溃
